name: Test 
"on":
  push:
jobs:
  Test-Steps:
    runs-on: ubuntu-latest
    steps:
      - name: 1
        continue-on-error: true
        if: success() || failure()
        id: setup_1
        run: date; false
      - name: 2
        id: setup_2
        continue-on-error: true
        if: success() || failure()
        run: |
          echo 'foo bar $USER baz' >file.txt
      - name: 3
        id: setup_3
        continue-on-error: true
        if: success() || failure()
        run: cat file.txt | envsubst
      - name: 4
        id: setup_4
        continue-on-error: true
        if: success() || failure()
        run: date; false
      - name: 5
        id: setup_result
        continue-on-error: true
        if: success() || failure()
        run: |
          echo "${{ join(steps.*.conclusion, ' ') }}" | xargs -n1
      - name: Final step
        if: success() && steps.setup_result.conclusion == 'success'
        run: date; true
